---
title: "02-power-analysis-glm-m-s"
format: html
editor: source
---

# Power analysis using GLM-M(s)

When is the last time that you read an ecological study that performed some kind of power analysis before conducting an experiment? Honestly, I'm not sure I've ever read one which is incredible given the number of ecological experiments that are conducted and published. Why is this the case? This definitely has something to do with the statistical education we receive as ecologists which tends not to emphasise this kind of thing. Moreover, if it is emphasised, then it's often not clear how to go about it with complex experimental designs that have many layers of nesting etc.

This problem came up during a discussion with a friend about someone who was struggling to finish their PhD. Long-story short, she conducted a physiology experiment with noisy measurements and low replication. This means that she is struggling to get it published which is delaying her graduation. I immediately thought: Wow that sucks but that this experiment should never have been done. The physiological measurements they take in the lab are inherently noisy (according to my friend). Moreover, the measurements are a lot of work to take which means that simply cannot get high replication with them. Using simulation-based power analysis, we could have determined *a priori* that it would be very difficult to get interpretable results from such an experiment and saved everyone a lot of time, stress and money. In my view, if an experiment is very unlikely to yield interpretable results, it should not be done. Rather, the focus should be on improving the measurements or finding more efficient ways to take the measurements before such an experiment could be conducted. 

So, in this post, I'm going to go through how we can use simulation perform power analyses for arbitrarily complex experimental designs.






